Init.d scripts for every neat service adapted for Debian based distro

diff --git a/init.d/openstack-neat-local-manager b/init.d/openstack-neat-local-manager
--- a/init.d/openstack-neat-local-manager
+++ b/init.d/openstack-neat-local-manager
@@ -23,7 +23,6 @@
 #              messages to the global manager.
 ### END INIT INFO
 
-#. /etc/rc.d/init.d/functions
 . /lib/lsb/init-functions
 
 PYTHONPATH=/usr/lib/python2.7/site-packages
@@ -39,85 +38,78 @@ logfile="$logdir/local-manager-service.log"
 
 [ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
 
-#lockfile=/var/lock/subsys/$prog
 lockdir="/var/lock/subsys"
 lockfile="$lockdir/$prog"
 
-start() {
-    [ -x $exec ] || exit 5
-    [ -f $config ] || exit 6
-    echo -n $"Starting $prog: "
-    mkdir -p $piddir
-    mkdir -p $logdir
-    mkdir -p $lockdir
-    #daemon --user root --pidfile $pidfile "$exec &>$logfile & echo \$! > $pidfile"
-    start-stop-daemon --start --quiet --chuid root --make-pidfile --pidfile $pidfile --background --startas /bin/bash -- -c "exec $exec > $logfile 2>&1"
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+[ -x $DAEMON ] || exit 0
+
+for i in ${lockdir} ${piddir} ; do
+        [ ! -d ${i} ] && mkdir -p ${i}
+done
+
+do_start() {
+        start-stop-daemon --start \
+                        --background --quiet \
+                        --chuid root \
+                        --make-pidfile --pidfile $pidfile \
+                        --startas $exec \
+                        --test > /dev/null \
+                        || return 1
+        start-stop-daemon --start \
+                        --background --quiet \
+                        --chuid root \
+                        --make-pidfile --pidfile $pidfile \
+                        --startas /bin/bash \
+                        -- -c "exec $exec > $logfile 2>&1" \
+                        || return 2
 }
 
-stop() {
-    echo -n $"Stopping $prog: "
-    #killproc -p $pidfile $prog
-    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE    
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && rm -f $lockfile && rm -f $pidfile
-    return $retval
+do_stop() {
+        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pidfile
+        RETVAL=$?
+        rm -f $pidfile
+        return "$RETVAL"
 }
-
-restart() {
-    stop
-    start
-}
-
-reload() {
-    restart
-}
-
-force_reload() {
-    restart
-}
-
-rh_status() {
-    status -p $pidfile $prog
-}
-
-rh_status_q() {
-    rh_status >/dev/null 2>&1
-}
-
 
 case "$1" in
-    start)
-        rh_status_q && exit 0
-        $1
+start)
+        log_daemon_msg "Starting $desc" "$prog"
+        do_start
+        case $? in
+                0|1) log_end_msg 0 ;;
+                2) log_end_msg 1 ;;
+        esac
+;;
+stop)
+        log_daemon_msg "Stopping $desc" "$prog"
+        do_stop
+        case $? in
+                0|1) log_end_msg 0 ;;
+                2) log_end_msg 1 ;;
+        esac
+;;
+status)
+        status_of_proc "$exec" "$prog" && exit 0 || exit $?
+;;
+restart|force-reload)
+        log_daemon_msg "Restarting $desc" "$prog"
+        do_stop
+        case $? in
+        0|1)
+                do_start
+                case $? in
+                        0) log_end_msg 0 ;;
+                        1) log_end_msg 1 ;; # Old process is still running
+                        *) log_end_msg 1 ;; # Failed to start
+                esac
         ;;
-    stop)
-        rh_status_q || exit 0
-        $1
-        ;;
-    restart)
-        $1
-        ;;
-    reload)
-        rh_status_q || exit 7
-        $1
-        ;;
-    force-reload)
-        force_reload
-        ;;
-    status)
-        rh_status
-        ;;
-    condrestart|try-restart)
-        rh_status_q || exit 0
-        restart
-        ;;
-    *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
-        exit 2
+        *) log_end_msg 1 ;; # Failed to stop
+        esac
+;;
+*)
+        echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
+        exit 3
+;;
 esac
-exit $?
+
+exit 0
